### PR TITLE
Don't rely on deprecated save-state and set-output commands

### PR DESCRIPTION
**Pull request by JMorinPS**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Apply https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
| Type?             | refactor
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | 
| Sponsor company   | PrestaShop Corp
| How to test?      | CI should run as expected

### CODE REVIEW

**Comment by JMorinPS** [comment]
Original ticket
https://forge.prestashop.com/browse/INFRA-1157

**Review by BenjaminVouillaume — APPROVED** [review]

**Review by elodie-bil3 — APPROVED** [review]

**Review by matks — APPROVED** [review]
I updated the PR title and description to make it clear what is being done here

Unfortunately I do not know how this app is deployed. I would like that we verify the modified GitHub action scripts work well at least on integration.

@matthieu-rolland maybe you can help us?

**Comment by matks** [comment]
On https://github.com/PrestaShop/distribution-api we have a nice workflow explanation in the README, is it the same on this repo?

**Review by boherm — APPROVED** [review]

**Comment by JMorinPS** [comment]
Should we give a try with `integration-deployment` label ?

**Comment by JMorinPS** [comment]
Looks like integration workflows is handling the tag with new output syntax
image

**Comment by JMorinPS** [comment]
Waiting for a final go before merging

**Comment by matks** [comment]
Good to me 👍 thanks for the integration test. We merge!

**Pull request merged**
